# Generated by Django 4.2 on 2023-05-05 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=150)),
                ('definition', models.TextField()),
                ('measurement_unit', models.CharField(choices=[('Per', 'Percentage'), ('Num', 'Number')], max_length=10)),
                ('aggregation_level', models.CharField(choices=[('Dis', 'District'), ('Reg', 'Regional'), ('Nat', 'National')], max_length=10)),
                ('reporting_period', models.DateField(auto_now=True)),
                ('responsible_party', models.CharField(max_length=500)),
                ('level', models.CharField(choices=[('Inp', 'Input'), ('Outp', 'Output'), ('Outc', 'Outcome'), ('Inpc', 'Inpact')], max_length=10)),
                ('data_source', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='indicatorDataApp.country')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=5)),
                ('value_type', models.CharField(choices=[('C', 'Computed'), ('I', 'Inputted')], max_length=10)),
                ('level', models.CharField(choices=[('Dis', 'District'), ('Reg', 'Regional'), ('Nat', 'National')], default='Nat', max_length=10)),
                ('compute_format', models.CharField(choices=[('Ave', 'Average'), ('Net', 'Net'), ('Mean', 'Mean'), ('Mdn', 'Median')], default='Net', max_length=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='indicatorDataApp.country')),
            ],
        ),
        migrations.CreateModel(
            name='NationalIndicatorVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('indicator_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='national_var', to='indicatorDataApp.indicatorvariable')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=3)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='indicatorDataApp.country')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(auto_now_add=True)),
                ('inputted_value', models.DecimalField(decimal_places=2, default=None, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='RegionalIndicatorVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('national_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_vars', to='indicatorDataApp.nationalindicatorvariable')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='indicatorDataApp.region')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(auto_now_add=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='indicatorDataApp.indicator')),
            ],
        ),
        migrations.AddField(
            model_name='indicator',
            name='variables',
            field=models.ManyToManyField(blank=True, related_name='indicators', to='indicatorDataApp.indicatorvariable'),
        ),
        migrations.CreateModel(
            name='DistrictIndicatorVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('regional_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_vars', to='indicatorDataApp.regionalindicatorvariable')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=7)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='indicatorDataApp.region')),
            ],
        ),
        migrations.CreateModel(
            name='RegionalVarValue',
            fields=[
                ('value_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='indicatorDataApp.value')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_models', to='indicatorDataApp.regionalindicatorvariable')),
            ],
            bases=('indicatorDataApp.value',),
        ),
        migrations.CreateModel(
            name='NationalVarValue',
            fields=[
                ('value_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='indicatorDataApp.value')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_models', to='indicatorDataApp.nationalindicatorvariable')),
            ],
            bases=('indicatorDataApp.value',),
        ),
        migrations.CreateModel(
            name='DistrictVarValue',
            fields=[
                ('value_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='indicatorDataApp.value')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_models', to='indicatorDataApp.districtindicatorvariable')),
            ],
            bases=('indicatorDataApp.value',),
        ),
    ]
