# Generated by Django 4.2 on 2023-05-05 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicatorDataApp', '0002_alter_country_options_alter_country_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationalindicatorvariable',
            name='indicator_var',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='national_var', to='indicatorDataApp.indicatorvariable'),
        ),
    ]
