# Generated by Django 4.2 on 2023-05-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicatorDataApp', '0003_alter_nationalindicatorvariable_indicator_var'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='data_source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='responsible_party',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
