# Generated by Django 4.2 on 2023-05-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicatorDataApp', '0004_alter_indicator_data_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='conputing_formula',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
