# Generated by Django 4.2 on 2023-05-06 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicatorDataApp', '0005_indicator_conputing_formula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicator',
            old_name='conputing_formula',
            new_name='computing_formula',
        ),
    ]
