# Generated by Django 4.2 on 2023-05-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicatorDataApp', '0006_rename_conputing_formula_indicator_computing_formula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='computing_formula',
            field=models.CharField(blank=True, help_text='Not useful if only one variable is selected. Leave blank to use addtion of all varibles.', max_length=250, null=True),
        ),
    ]
