# Generated by Django 4.2 on 2023-05-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicatorDataApp', '0007_alter_indicator_computing_formula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='aggregation_level',
        ),
        migrations.AddField(
            model_name='indicator',
            name='measurement_level',
            field=models.CharField(choices=[('Inp', 'Input'), ('Outp', 'Output'), ('Outc', 'Outcome'), ('Inpc', 'Inpact')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='level',
            field=models.CharField(choices=[('Dis', 'District'), ('Reg', 'Regional'), ('Nat', 'National')], max_length=10, null=True),
        ),
    ]
