# Generated by Django 4.2 on 2023-05-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicatorDataApp', '0008_remove_indicator_aggregation_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorvalue',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='computing_formula',
            field=models.CharField(blank=True, help_text='Not useful if only one variable is selected.                                            Leave blank to use addtion of all varibles.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='indicatorvalue',
            name='period',
            field=models.DateField(),
        ),
    ]
