# Generated by Django 4.2 on 2023-05-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicatorDataApp', '0009_indicatorvalue_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='reporting_period',
        ),
        migrations.AddField(
            model_name='indicator',
            name='measurement_freq',
            field=models.CharField(choices=[('Bien', 'Biennial'), ('Yr', 'Yearly'), ('Bia', 'Biannually'), ('Mt', 'Monthly'), ('Qr', 'Quarterly'), ('Wk', 'Weekly'), ('Dy', 'Daily'), ('Hr', 'Hourly')], max_length=10, null=True),
        ),
    ]
